/***********************************************************************************
 **
 ** Atari++ emulator (c) 2002 THOR-Software, Thomas Richter
 **
 ** $Id: instruction.cpp,v 1.3 2015/05/21 18:52:40 thor Exp $
 **
 ** In this module: Definition of the instruction primitive for the disassembler
 ** This table is generated by the CPU, and used by the disassembler.
 **********************************************************************************/
