/***********************************************************************************
 **
 ** Atari++ emulator (c) 2002 THOR-Software, Thomas Richter
 **
 ** $Id: instruction.cpp,v 1.2 2008-05-22 13:03:54 thor Exp $
 **
 ** In this module: Definition of the instruction primitive for the disassembler
 ** This table is generated by the CPU, and used by the disassembler.
 **********************************************************************************/
