/* types.h.  Generated by configure.  */
/* types.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if exception handling works */
#define EXCEPTIONS_WORK 1

/* Define to 1 if curses provides the COLS global variable */
/* #define HAS_COLS 1 */

/* Define to 1 if const_cast<> works */
#define HAS_CONST_CAST 1

/* Define to 1 if EAGAIN is a valid errno value */
#define HAS_EAGAIN_DEFINE 1

/* Define to 1 if ELOOP is a valid errno value */
/* #define HAS_ELOOP_DEFINE 1*/

/* Define to 1 if ETXTBSY is a valid errno value */
/* #define HAS_ETXTBSY_DEFINE 1*/

/* Define to 1 if integer constants are valid template arguments */
#define HAS_INT_TEMPLATE_ARGS 1

/* Define to 1 if templated subclasses are correctly in the namespace of the
   parent class */
#define HAS_LOCAL_TEMPLATES 1

/* Define to 1 if initializers of static const integral members work */
#define HAS_MEMBER_INIT 1

/* Define to 1 if subclasses have access to private members */
#define HAS_PRIVATE_ACCESS 1

/* Define to 1 if the ALSA NEW_HW_PARAMS_API is available */
/* #define HAS_PROPER_ALSA 1 */

/* Define to 1 if struct timeval is available */
/* #define HAS_STRUCT_TIMEVAL 1 */

/* Define to 1 if casting in template arguments work */
#define HAS_TEMPLATE_CASTS 1

/* Define to 1 if the __null keyword is available */
/* #define HAS__NULL_TYPE 1 */

/* Define to 1 if you have the <alsa/asoundlib.h> header file. */
/* #define HAVE_ALSA_ASOUNDLIB_H 1 */

/* Define to 1 if you have the <atarisio.h> header file. */
/* #define HAVE_ATARISIO_H 1 */

/* Define to 1 if you have the <bstrings.h> header file. */
/* #undef HAVE_BSTRINGS_H */

/* Define to 1 if you have the <bstring.h> header file. */
/* #undef HAVE_BSTRING_H */

/* Define to 1 if you have the `cfmakeraw' function. */
/* #define HAVE_CFMAKERAW 1*/

/* Define to 1 if you have the `cfsetispeed' function. */
/* #define HAVE_CFSETISPEED 1*/

/* Define to 1 if you have the `cfsetospeed' function. */
#define HAVE_CFSETOSPEED 1

/* Define to 1 if you have the `chmod' function. */
/*#define HAVE_CHMOD 1*/

/* Define to 1 if you have the `close' function. */
#define HAVE_CLOSE 1

/* Define to 1 if you have the `creat' function. */
#define HAVE_CREAT 1

/* Define to 1 if you have the <curses.h> header file. */
/*#define HAVE_CURSES_H 1*/

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
/*#define HAVE_DIRENT_H 1*/

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the `exp' function. */
#define HAVE_EXP 1

/* Define to 1 if you have the `cos' function. */
#define HAVE_COS 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `fork' function. */
/* #define HAVE_FORK 1 */

/* Define to 1 if you have the `getenv' function. */
#define HAVE_GETENV 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `gzopen' function. */
#define HAVE_GZOPEN 1

/* Define to 1 if you have the `halfdelay' function. */
/*#define HAVE_HALFDELAY 1*/

/* Define to 1 if you have the `initscr' function. */
/*#define HAVE_INITSCR 1*/

/* Define to 1 if you have the <inttypes.h> header file. */
/*#define HAVE_INTTYPES_H 1*/

/* Define to 1 if you have the `ioctl' function. */
#define HAVE_IOCTL 1

/* Define to 1 if you have the `isascii' function. */
#define HAVE_ISASCII 1

/* Define to 1 if you have the `isatty' function. */
#define HAVE_ISATTY 1

/* Define to 1 if you have the <linux/ioctl.h> header file. */
/* #define HAVE_LINUX_IOCTL_H 1*/

/* Define to 1 if you have the <linux/joystick.h> header file. */
/* #define HAVE_LINUX_JOYSTICK_H 1*/

/* Define to 1 if you have the <linux/serial.h> header file. */
/* #define HAVE_LINUX_SERIAL_H 1*/

/* Define to 1 if you have the `localtime' function. */
#define HAVE_LOCALTIME 1

/* Define to 1 if you have the `log' function. */
#define HAVE_LOG 1

/* Define to 1 if you have the `log10' function. */
#define HAVE_LOG10 1

/* Define to 1 if the system has the type `long long'. */
#define HAVE_LONG_LONG 1

/* Define to 1 if your system has a working `malloc' function. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the `memchr' function. */
#define HAVE_MEMCHR 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the <ncurses_dll.h> header file. */
/* #define HAVE_NCURSES_DLL_H 1*/

/* Define to 1 if you have the <ncurses.h> header file. */
/* #define HAVE_NCURSES_H 1*/

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the `newterm' function. */
#define HAVE_NEWTERM 1

/* Define to 1 if you have the `open' function. */
#define HAVE_OPEN 1

/* Define to 1 if you have the `png_create_info_struct' function. */
#define HAVE_PNG_CREATE_INFO_STRUCT 1

/* Define to 1 if you have the `png_create_write_struct' function. */
#define HAVE_PNG_CREATE_WRITE_STRUCT 1

/* Define to 1 if you have the <png.h> header file. */
/* #define HAVE_PNG_H 1*/

/* Define to 1 if you have the `png_write_chunk' function. */
/* #define HAVE_PNG_WRITE_CHUNK 1*/

/* Define to 1 if you have the `pow' function. */
#define HAVE_POW 1

/* Define to 1 if you have the `read' function. */
#define HAVE_READ 1

/* Define to 1 if you have the `SDL_Init' function. */
#define HAVE_SDL_INIT 1

/* Define to 1 if you have the `SDL_InitSubSystem' function. */
#define HAVE_SDL_INITSUBSYSTEM 1

/* Define to 1 if you have the `SDL_JoystickOpen' function. */
#define HAVE_SDL_JOYSTICKOPEN 1

/* Define to 1 if you have the `SDL_OpenAudio' function. */
#define HAVE_SDL_OPENAUDIO 1

/* Define to 1 if you have the <SDL/SDL.h> header file. */
#define HAVE_SDL_SDL_H 1

/* Define to 1 if you have the `SDL_SetVideoMode' function. */
#define HAVE_SDL_SETVIDEOMODE 1

/* Define to 1 if you have the `select' function. */
/* #define HAVE_SELECT 1*/

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `snd_pcm_open' function. */
/*#define HAVE_SND_PCM_OPEN 1*/

/* Define to 1 if you have the `snd_pcm_writei' function. */
/*#define HAVE_SND_PCM_WRITEI 1*/

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if `stat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_STAT_EMPTY_STRING_BUG */

/* Define to 1 if you have the <stat.h> header file. */
/* #undef HAVE_STAT_H */

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
/*#define HAVE_STDINT_H 1*/

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
/* #define HAVE_STRINGS_H 1*/

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the `strtod' function. */
#define HAVE_STRTOD 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/soundcard.h> header file. */
/*#define HAVE_SYS_SOUNDCARD_H 1*/

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
/*#define HAVE_SYS_TIME_H 1*/

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `tcdrain' function. */
#define HAVE_TCDRAIN 1

/* Define to 1 if you have the `tcflush' function. */
#define HAVE_TCFLUSH 1

/* Define to 1 if you have the `tcgetattr' function. */
#define HAVE_TCGETATTR 1

/* Define to 1 if you have the `tcsetattr' function. */
#define HAVE_TCSETATTR 1

/* Define to 1 if you have the <termios.h> header file. */
/* #define HAVE_TERMIOS_H 1 */

/* Define to 1 if you have the `time' function. */
#define HAVE_TIME 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
/* #define HAVE_UNISTD_H 1*/ 

/* Define to 1 if you have the <unix.h> header file. */
/* #undef HAVE_UNIX_H */

/* Define to 1 if you have the `unlink' function. */
#define HAVE_UNLINK 1

/* Define to 1 if the system has the type `unsigned long long'. */
#define HAVE_UNSIGNED_LONG_LONG 1

/* Define to 1 if you have the `usleep' function. */
/*#define HAVE_USLEEP 1*/

/* Define to 1 if you have the <utime.h> header file. */
/*#define HAVE_UTIME_H 1*/

/* Define to 1 if you have the `vfork' function. */
/*#define HAVE_VFORK 1*/

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the `vsnprintf' function. */
/*#define HAVE_VSNPRINTF 1*/

/* Define to 1 if `fork' works. */
/* #define HAVE_WORKING_FORK 1*/

/* Define to 1 if `vfork' works. */
/* #define HAVE_WORKING_VFORK 1*/

/* Define to 1 if you have the `write' function. */
#define HAVE_WRITE 1

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* Define to 1 if the system has the type `__int64'. */
/* #define HAVE___INT64*/

/* Define to 1 if `lstat' dereferences a symlink specified with a trailing
   slash. */
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "thor@math.tu-berlin.de"

/* Define to the full name of this package. */
#define PACKAGE_NAME "atari++"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "atari++ 1.81"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "atari--"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.81"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if SIGSEGV signal works */
#define SIGSEG_WORKS 1

/* Define to 1 if required argument to signal handlers is "..." */
/* #undef SIG_ARG_TYPE_DOTS */

/* Define to 1 if required argument to signal handlers is int */
#define SIG_ARG_TYPE_INT 1

/* Define to 1 if the `S_IS*' macros in <sys/stat.h> do not work properly. */
/* #undef STAT_MACROS_BROKEN */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
/* #define TIME_WITH_SYS_TIME 1*/

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
/* #undef inline */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define as `fork' if `vfork' does not work. */
/* #undef vfork */

/* Set this if the SDL timer functions shall be used */
#define USE_SDL_TIMER 1

/* Define this if the console must be opened explicitly */
#define MUST_OPEN_CONSOLE 1

/* Define this if we should provide the built-in monitor */
#define BUILD_MONITOR 1

/* Define this in case the DirectX sound interface is available */
#define HAVE_DXSOUND 1

/* Define to the size of char in bytes */
#define SIZEOF_CHAR 1

/* Define to the size of short in bytes */
#define SIZEOF_SHORT 2

/* Define to the size of int in bytes */
#define SIZEOF_INT 4

/* Define to the size of long in bytes */
#define SIZEOF_LONG 4

/* Define to the size of __int64 */
#define SIZEOF__INT64 8

/* Define to the size of long long */
#define SIZEOF_LONG_LONG 8
